### ISSUE TITLE
wrong

### ISSUE THREAD

**Issue by ChinaBuleSky** [o5zereth/MurderMystery#1]
There is an error on lines 585-594
                **foreach (Lift lift in Map.Lifts)
                {
                    switch (lift.Type())
                    {
                        case Exiled.API.Enums.ElevatorType.LczA:
                        case Exiled.API.Enums.ElevatorType.LczB:
                            lift.Network_locked = true;
                            continue;
                    }
                }**

**Comment by o5zereth** [comment]
Could you please elaborate on the error?

**Comment by o5zereth** [comment]
When EXILED 5.0 is fully released, I will make an update,

**Comment by ChinaBuleSky** [comment]
oh,fine
