### ISSUE TITLE
I don't know how to use

### ISSUE THREAD

**Issue by Galinhadofuturo** [o5zereth/MurderMystery#3]
I tried to use the plugin but I don't know how it works. I followed the instructions in the read me and the plugin still did not work

**Comment by o5zereth** [comment]
Could you elaborate?

There are many possibilities on what you may be encountering.

Error in console?
Wrong version?
Command wont run?

**Comment by Galinhadofuturo** [comment]
when trying to start game mode using "mm enable" it just doesn't start. The same seems to be enabled but I don't see any changes in the game.
